
import "./globals.css";
import MainContainer from "../../components/MainContainer";



export const metadata = {
  title: "Aula NextJs",
  description: "Generated by create next app",
  
};

export default function RootLayout({children}) {
  return (
    <>
  
      <html lang="pt-Br">
        <MainContainer>
        {children}
        </MainContainer>
    </html >

    
      
    
    </>
  );
}
